version: "3.8"

services:
  products-api:
    build:
      context: .
    container_name: products-api
    restart: always
    ports:
    - 8000:8000
    depends_on:
      - products-db
  products-db:
    image: postgres:13.3-alpine
    restart: always
    container_name: products-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/app/postgres/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=1q2w3e
