name: Run CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check formatting
      uses: Jerome1337/gofmt-action@v1.0.4

    - name: Fetch dependencies
      run:  go mod download

    - name: Build
      run: make build

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

    - name: Run functional tests
      run:  make test
